image: cypress/browsers:node12.0.0-chrome73

stages:
   - install
   - build
   - test

# NEW
variables:
   npm_config_cache: "$CI_PROJECT_DIR/.npm"
   CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
   key:
     files:
        - package.json
   paths:
      - .npm
      - cache/Cypress
      - node_modules
# END NEW

install_dependencies:
  stage: install
  script:
    - npm ci --cache .npm --prefer-offline
  

bundle_app:
  stage: build
  script:
  - npm run build
  artifacts:
   paths:
    - build/


build_jobX:
  stage: build
  only:
    - develop
  script:
    - echo "build job X on demoBranch works"

exercise_job:
  stage: build
  only:
    -main
  script:
    - echo "Test exercise stage"

e2etest:    
  stage: test
  script:
    - echo "Run tests in headless mode"
    - npm run start:ci

test_jobX:
  stage: test
  only:
    - main
    - branchX
  script:
    - echo "Run test job X"