swagger: '2.0'
info:
  description: Movies-API
  version: 1.0.0
  title: Movies API
  # put the contact info for your development or API team
  contact:
    email: 20084586@mail.wit.ie

# tags are used for organizing operations
tags:
- name: discover
  description: Using the 'discover' section in TMDB
- name: upcoming
  description: Using the 'upcoming' section in TMDB
- name: toprated
  description: Using the 'toprated' section in TMDB
- name: tvshows
  description: Using the 'tvshows' section in TMDB
- name: movie
  description: Returns movie by ID from TMDB
- name: show
  description: Returns show by ID from TMDB

paths:
  /api/movies/tmdb/discover:
    get:
      tags:
      - discover
      summary: new movies
      description: |
        Returns object with nested array of new movies.
      produces:
      - application/json
      responses:
        200:
          description: Success
        401: 
          description: Unauthorized
        404: 
          description: Resource not found
          
  /api/movies/tmdb/upcoming:
    get:
      tags:
      - upcoming
      summary: upcoming movies
      description: |
        Returns object with nested array of upcoming movies.
      produces:
      - application/json
      responses:
        200:
          description: Success
        401: 
          description: Unauthorized
        404: 
          description: Resource not found
          
  /api/movies/tmdb/toprated:
    get:
      tags:
      - toprated
      summary: top rated movies
      description: |
        Returns object with nested array of top rated movies.
      produces:
      - application/json
      responses:
        200:
          description: Success
        401: 
          description: Unauthorized
        404: 
          description: Resource not found
          
  /api/shows/tmdb/tvshows:
    get:
      tags:
      - tvshows
      summary: popular tv shows
      description: |
        Returns object with nested array of popular tv shows.
      produces:
      - application/json
      responses:
        200:
          description: Success
        401: 
          description: Unauthorized
        404: 
          description: Resource not found
      
  /api/movies/tmdb/movies/{id}:
    get:
      tags:
      - movie
      summary: movie details
      parameters:
        - name: id
          in: path
          type: integer
          required: true
          description: The ID of the movie to return.
          
      description: |
        Returns object with details of specific movie
      produces:
      - application/json
      responses:
        200:
          description: Success
        401: 
          description: Unauthorized
        404: 
          description: Resource not found
  /api/shows/tmdb/tvshows/{id}:
    get:
      tags:
      - show
      summary: show details
      parameters:
        - name: id
          in: path
          type: integer
          required: true
          description: The ID of the show to return.
          
      description: |
        Returns object with details of specific movie
      produces:
      - application/json
      responses:
        200:
          description: Success
        401: 
          description: Unauthorized
        404: 
          description: Resource not found


            
        
  
  
    